title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
timezone: UTC
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

markdown: kramdown
theme: minima
future: true
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

collections:
  posts:
    output: true
    directory: _posts/posts
    permalink: /blog/posts/:year-:month-:day-:title.html

  api:
    output: true
    directory: _api
    permalink: /api/:title.json

  songs:
    output: true
    directory: _songs
    permalink: /songs/:title.html

  shows:
    output: true
    directory: _shows
    permalink: /shows/:year-:month-:day-:slug.html

exclude: [node_modules, webpack.config.js]

defaults:
  -
    scope:
      type: 'posts'
      path: ''
    values:
      react: 'post'

  -
    scope:
      type: 'shows'
      path: ''
    values:
      layout: 'show'
